### ISSUE TITLE
Add to the README.md build section.

### ISSUE THREAD

**Issue by zatochi** [ixrock/XTranslate#14]
Hi. First of all thanks for the great extension.

I'm trying to use this extension from source code, but I'm not a web developer and I don't know how to compile TypeScript into JavaScript.

It'll be great if was build section in README.md.

**Comment by ixrock** [comment]
Hello there! 
If installing the app from chrome-store doesn't fit to your needs, you can try to run `yarn && yarn build`.
This app not intended to be used from source code, so there is no need in this command in readme file.

**Comment by zatochi** [comment]
Thanks for a quick response.
