### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by yora-gets** [ixrock/XTranslate#15]
Hello I had started frequently get 503 error. Please fix it.

![503](https://user-images.githubusercontent.com/10236846/44850738-cfef2c80-ac66-11e8-9ae7-b225eaf1e2f2.JPG)

**Comment by ixrock** [comment]
@yora-gets it's not a problem of extension itself. Google might block suspicious traffic in some cases, for example if you type in the window text quite slowly.
When you see `503` error just use another translation vendor for a while (Yandex or Bing).

**Comment by yora-gets** [comment]
Sad, but thanks for answer.





​
​
С ув. Юрий Гец
​Полезный к
опирайтер
Посетите мой сайт <https://yurii-hets.blogspot.com/>

2018-08-30 15:23 GMT+03:00 ixrock <notifications@github.com>:

**Comment by yora-gets** [comment]
Sad, but thanks.

**Comment by yora-gets** [comment]
> @yora-gets it's not a problem of extension itself. Google might block suspicious traffic in some cases, for example if you type in the window text quite slowly.
> When you see `503` error just use another translation vendor for a while (Yandex or Bing).

Thanks
