### ISSUE TITLE
Text "Common" in settings not shown

### ISSUE THREAD

**Issue by Etamuk** [ixrock/XTranslate#17]
The text from "setting_title_common" (string from language file) is not shown in settings in extension-popup. Therefore is also not shown the translated text. Please see my screenshot.
Or maybe i am wrong? :-)

![Bildschirmfoto vom 2019-06-21 13-40-54](https://user-images.githubusercontent.com/20098065/59920472-e9967600-942a-11e9-93c5-085cd4111803.png)

**Comment by ixrock** [comment]
Yes, not everything should be shown from `messages.json`  :)
Basically I just didn't remove outdated/old texts from there..
