### ISSUE TITLE
Now that Edge Chromium has reached the beta stage, can we get XTranslate submitted to Microsoft Edge Add-ons?

### ISSUE THREAD

**Issue by ghost** [ixrock/XTranslate#21]
[Most popular extensions are already there.](https://microsoftedge.microsoft.com/insider-addons/category/EdgeExtensions) XTranslate seems to be fully compatible.

**Comment by ixrock** [comment]
Dunno, have to check fi Edge supports all required chrome apis..

**Comment by SergeyTverye** [comment]
It looks like that most of the popular extensions already appeared in the Microsoft Store, so I think there are no problems with API now. Your translation extension is the best, and i am really looking forward to see you in the new Store :)

**Comment by ixrock** [comment]
@SergeyTverye you can install the extension directly from Chrome Web Store.
I just checked this and everything seems to work.

![image](https://user-images.githubusercontent.com/6377066/79428174-7455ec00-7fce-11ea-9f44-21a555e43018.png)

**Comment by SergeyTverye** [comment]
@ixrock I am doing so at the moment, but this forces the browser connect with the google store for updates. I would rather share my data with only one corporation, if I have to do this. In any case, this is just a wish. I understand that you may not have free time for this.

**Comment by StrangePeanut** [comment]
I’ve switched to another extension, since I’d rather not use the Chrome Web Store.

**Comment by ixrock** [comment]
Published to Microsoft Edge Add-ons
https://microsoftedge.microsoft.com/addons/detail/cinfaflgbaachkaamaeglolofeahelkd

**Comment by StrangePeanut** [comment]
@ixrock You're awesome dude.
