### ISSUE TITLE
Editable list of languages

### ISSUE THREAD

**Issue by SergeyTverye** [ixrock/XTranslate#28]
Hi! Just an idea, maybe in the future you can make an editable list of languages? For example, I often translate from English, German, Slovak and Turkish, as a result I have to very often leaf through this long list for choose one or another language. It would be very cool if I could leave only 5 languages I need in the list and not scroll any more. 

It may also be interesting for you to add this vendor https://www.deepl.com/translator

Thanks for your work! :)

**Comment by ixrock** [comment]
When you open languages select box you can quickly navigate by pressing first letter of the preferred language.
~Another option: you can save language-pairs to favourites for quick access as well.~
But... maybe better to add "last used languages" to the top of list? (this one need to implement)

P.S deepl translator api is not free to use, so no plans to add.

**Comment by SergeyTverye** [comment]
> But... maybe better to add "last used languages" to the top of list? (this one need to implement)

It would be pretty handy! Or, alternatively, when user press the first letter of the language, so that the scrolling is from the first match and **below**, and not so that when you press, for example, the letter S, only one language per letter S would be visible at the bottom of the list. Oh ... Now I realized that this is the problem of the second half of the list of languages. :)

**Comment by ixrock** [comment]
> Hi! Just an idea, maybe in the future you can make an editable list of languages? For example, I often translate from English, German, Slovak and Turkish, as a result I have to very often leaf through this long list for choose one or another language. It would be very cool if I could leave only 5 languages I need in the list and not scroll any more.

Starting v.2.60 there is a new select component for choosing source / target languages (it also supports quick filtering languages, just start typing when it's focused).

<img width="581" alt="Screenshot 2022-01-20 at 20 49 48" src="https://user-images.githubusercontent.com/6377066/150403033-e6154175-2133-4118-9e95-f450bb9ff234.png">

To mark/unmark language as favourite (shown on top of languages list) you can click the option with pressed `Cmd` (Mac) or `Alt+Shift` (Windows/Linux).
