### ISSUE TITLE
Xtranslate for Opera 12

### ISSUE THREAD

**Issue by VinylNix** [ixrock/XTranslate#3]
Greetings,

I want to start using this extension for my opera 12.14, but the link you've provided in the description is no longer working: https://addons.opera.com/package/download/revision/xtranslate/2.8.56/3/

Are there any other ways to get it?

**Comment by ixrock** [comment]
Hi there! 
This link works for me and suggest to download *.oex file.
Anyway, the extension doesn't support Opera 12 officially anymore.
Try to go to https://addons.opera.com/en/extensions/details/xtranslate/ to find working download link, otherwise cannot help.
