### ISSUE TITLE
Перевод на украинский

### ISSUE THREAD

**Issue by ViktorOn** [ixrock/XTranslate#39]
Просьба добавить папку для перевода на украинский в locales. И ещё (функциональное) - возможность поиска по буквам в списке языков.
_И чисто от себя - иконки соцсетей посередине бы..._

**Comment by ixrock** [comment]
Что значит добавить папку в locales?) А перевод кто будет делать? Запилите пиар с переводом где будет создана нужные папки и файл`_locales/uk/messages.json`. По поводу поиска - он уже работает, нужно просто открыть список языков и можно начинать печатать (будет фильтрация списка)

<img width="566" alt="Screenshot 2022-02-03 at 18 10 23" src="https://user-images.githubusercontent.com/6377066/152381520-7d92ef36-a56d-4c11-9a4f-946f72ccb138.png">

_Иконки соцсетей думаю вообще подчистить некоторые (вк/фб удалить)_

**Comment by ViktorOn** [comment]
> Что значит добавить папку в locales?) А перевод кто будет делать?

Ну в данном случае я буду. А вообще что мешает добавить папки и файлы даже без учёта этого? 5 самых популярных языков, например. Люди, которые помогут, со временем найдутся. По поводу поиска - понял, спасибо.

**Comment by ixrock** [comment]
Нету смысла никакого создавать пустые папки (они должны быть созданы авторами переводов либо я создам когда будем уже сам перевод).
Вот список поддерживаемых локалей https://developer.chrome.com/docs/webstore/i18n/
