### ISSUE TITLE
Popup Error (v 2.63.0)

### ISSUE THREAD

**Issue by starlingus** [ixrock/XTranslate#46]
STR:
1, Select any translation engine
2, Double click on string on webpage to translate

ER:
Translation appears (worked in 2.62.2)

AE:
: Data loading failed
Cannot read properties of undefined (reading 'sendMessage')

Thank You :)

![image](https://user-images.githubusercontent.com/87526209/163102001-c1eb2e5e-4ba0-4de1-8e3c-2aa0e3389eb2.png)

**Comment by ixrock** [comment]
Hello. 
Cannot reproduce the issue. What the browser & OS you using? Also what was the testing URL?

**Comment by starlingus** [comment]
Sorry I forgot to add this information. Chrome and Windows 11. After the
latest update of Chrome the issue is not present anymore.

Thank you



Dne pá 15. 4. 2022 15:08 uživatel Roman ***@***.***> napsal:
