### ISSUE TITLE
Incorrect working command "ctrl+c" in Google Chrome when plagin is activated

### ISSUE THREAD

**Issue by sprywilly** [ixrock/XTranslate#47]
When plagin is activated i can't use shortcuts like as "ctrl+c" in my browser. Problem starting after pressing key "ctrl"
Ubuntu ver.: 20.04
Google Chrome ver.: 100.0.4896.88
XTranslate ver.: 2.63.0

**Comment by ixrock** [comment]
Similar issue already detected & gonna be fixed soon. Thanks for feedback.
