### ISSUE TITLE
XTranslate is tracking users by redirecting via LinkSynergy including a unique tracking ID

### ISSUE THREAD

**Issue by StrangePeanut** [ixrock/XTranslate#51]
XTranslate 2.64.2 on Chrome has started to track users' browser activity by redirecting search results (and possibly more) via LinkSynergy including a unique tracking ID. It came to our attention due to LinkSynergy being null routed on our network.

Example hit: `http://click.linksynergy.com/deeplink?id=...&mid=...&subid=[[...]]&u1=[[...]]&murl=...`

XTranslate 2.64.0 on Edge appears to be unaffected (for now)

**Comment by StrangePeanut** [comment]
Relevant commit: https://github.com/ixrock/XTranslate/commit/54ff26a3b11b5cb7b61b202cf283533668c0334b

**Comment by ixrock** [comment]
What the topic of issue? :) 
Users are not tracked (as [adgoal.de](https://www.adgoal.de/) declares) and they use only `ClickID` and `OrderID`.
Also it's declared that current extension in partnership with adgoal.de in project's [Privacy policy](https://github.com/ixrock/XTranslate/blob/master/privacy-policy.md#final-statements).
If you're against this policy please delete and stop using `XTranslate` for now.

**Comment by ixrock** [comment]
@StrangePeanut in nexts releases we might add a "button" to disable this ads by user request or if it's not working in his network _(e.g. redirected url is not allowed by proxy server, etc)_
