### ISSUE TITLE
Extension clickjacking google results 

### ISSUE THREAD

**Issue by perguto** [ixrock/XTranslate#52]
XTranslate is clickjacking links to certain sites (e. g. Google results for Microsoft pages) to ad sites. Apparently this behavior corresponds to the recent "adgoal partnership" commit, but it can only be considered malicious as the update got pushed without any notification whatsoever and there's no mention of it in the Chrome store.

**Comment by ixrock** [comment]
Ok, we will add notice to chrome extension page description. This is legal and officially supported by extensions store. 

As declared by out partner [adgoal.de](https://www.adgoal.de/en/) search results affected only by adding small logos near links and might add 1-2 extra redirects before going to final's shop website (only `ClickId` and `OrderId` is taken in use). 
Here is example of added logo at the right by searching "buy shoes":

![telegram-cloud-photo-size-4-5814150078624021245-y](https://user-images.githubusercontent.com/6377066/171613832-fe59f3cc-524d-4c19-939e-5beb9caaddc0.jpg)

**@perguto If you against this policy please stop using the extension (as well as [forking and removing ads](https://github.com/perguto/XTranslate-without-malware)). This illegally and might be punished.**

**Comment by voltrare** [comment]
>**This illegally and might be punished.**

its not illegal as the project is open source and licensed with MIT license which allows modification of the project as long as the original license is included

https://opensource.org/licenses/MIT

**Comment by ixrock** [comment]
> > **This illegally and might be punished.**
> 
> its not illegal as the project is open source and licensed with MIT license which allows modification of the project as long as the original license is included
> 
> https://opensource.org/licenses/MIT

Alright, no worry, I've removed this dummy advertiser.
