### ISSUE TITLE
The pop-up window doesn't work on offline pages

### ISSUE THREAD

**Issue by tellator** [ixrock/XTranslate#54]
the translation icon is not displayed next to the highlighted text if the html page is on the local computer. Other ways to call a pop-up window (keyboard shortcut, for example) don't work either

**Comment by ixrock** [comment]
Your issue would be fixed if you enable checkbox "**Allow access to file URLs**" in the "**Details**" (of extension in the list of extensions at `chrome://extensions/` ?)

**Comment by ixrock** [comment]
@Ijkol so, I assume "offline pages" == "local pages" (which URL starting from `file://*`) right? If so you should enable checkbox ^, otherwise you cannot expect this extension to work offline.. _(except probably cases with saved dictionary words)_

**Comment by tellator** [comment]
> @Ijkol so, I assume "offline pages" == "local pages" (which URL starting from `file://*`) right? If so you should enable checkbox ^, otherwise you cannot expect this extension to work offline.. _(except probably cases with saved dictionary words)_

thank you, providing access to the file urls worked. Yes, I was referring specifically to local html files, when viewing them, the pop-up window did not work even with the Internet. Everything is fine now, thank you
