### ISSUE TITLE
Reverse translation option

### ISSUE THREAD

**Issue by zazomazzo** [ixrock/XTranslate#55]
I would like to see a "reverse translate option language" to chose from.
For example:
I like to have everything translated to English. But when I select English text I want it to be translated to German.

An additional item in the options to select this "reverse language" would be nice. :)

Keep up the great work. :)

**Comment by ixrock** [comment]
@zazomazzo please await new version (`>3.1`) in chrome store a bit later :)

<img width="636" alt="image" src="https://github.com/ixrock/XTranslate/assets/6377066/3fa1577b-4d1e-4b7b-ad0e-df8c37772915">
