### ISSUE TITLE
[Bug] Firefox browser begin work very slow.

### ISSUE THREAD

**Issue by gekasam** [ixrock/XTranslate#62]
When I installed this extension in my firebox with the tree style tab extension, the browser began to load for a very long time and slow down at some points.

**Comment by ixrock** [comment]
It's not officially supported. For firefox was uploaded `manifest.json` with `v2.0` which means soom gonna be outdated and not supports everything. but meanwhile current support of `v3.0` not fully implemented from firefox team.

**Consider current firefox uploaded version in firefox store as `raw-beta`, "if it works then it's already good somehow".**
See also issue #1

_Closing for now and waiting for full deprecation of manifest v2 and migrating to v3 when all ready from mozilla side._
