### ISSUE TITLE
Can a frontend library be used in this project to reduce the code?

### ISSUE THREAD

**Issue by HappyNinja2** [ixrock/XTranslate#63]
Can a frontend library (like MUI) be used in this project to remove codes for custom components such as Radio Button (https://github.com/ixrock/XTranslate/tree/master/src/components/radio) ? Thanks

**Comment by ixrock** [comment]
What? You suggest me to replace custom UI component to some random external UI lib/npm package?
There is no need in reducing the code. Thanks for caring..
