### ISSUE TITLE
PDF translate doesnt work

### ISSUE THREAD

**Issue by wewrere41** [ixrock/XTranslate#65]
Microsoft Edge 110.0.1587.63
Dual Monitor
Location option is auto

Online
Its sometimes shows in upper left in correct monitor and sometimes doesnt show any popup.  

Local
Sometimes its showing in left(wrong) monitor and generally doesnt show popup. I tried again with single screen but nothing changed.
![G](https://user-images.githubusercontent.com/45511976/222886085-be034eca-e297-45e0-9fe9-7c234359a4e2.png)

**Comment by ixrock** [comment]
fixed since `v5.0.0`
