### ISSUE TITLE
issue 456: data receive error.

### ISSUE THREAD

**Issue by Koharyy** [ixrock/XTranslate#66]
![image](https://user-images.githubusercontent.com/127120476/223140043-51d4d194-b7af-4d95-ac78-0733491a8d67.png)

Hello, this error appeared, I don't know how to fix it, it doesn't work only in the chrome browser. cookies, other data in the settings tried to clear, and set a translation delay(sorry my for my bad englisn)

**Comment by ixrock** [comment]
Никак не исправить. В приложении используется бесплатный ключ от Deepl с очень лимитированным количеством символов для перевода в месяц. После этого наступает такая ошибка пока не обновится до след. месяца.

**Что нужно сделать?** 

1. зарегистрироваться https://www.deepl.com/en/signup/ 
1. получить свой личный ключ доступа
1. ввести ключ в настройках расширения

**Comment by gtumanyan** [comment]
> * получить свой личный ключ доступа

Как получить ключ? При нажатии кнопки [Sign up for free](https://www.deepl.com/pro-api?cta=header-pro-api) ничего не происходит.

**Comment by ixrock** [comment]
> Как получить ключ? При нажатии кнопки [Sign up for free](https://www.deepl.com/pro-api?cta=header-pro-api) ничего не происходит.

@gtumanyan  Внизу страницы варианты регистраций ("DeepL API Free", "DeepL API Pro" & "Custom")
При регистрации бесплатно у меня такая ссылка https://www.deepl.com/pro-checkout/account?productId=1200&yearly=false&trial=false

**Comment by gtumanyan** [comment]
@ixrock К сожалению России в списке нет, а для других стран требуется проверка соотвествующей банковской карты
