### ISSUE TITLE
LibreTranslate

### ISSUE THREAD

**Issue by scavru** [ixrock/XTranslate#69]
Would you like to consider adding [LibreTranslate ](https://github.com/LibreTranslate/LibreTranslate) to the supported vendors? It would be nice to translate locally without sharing data with corporations.

**Comment by ixrock** [comment]
> Would you like to consider adding [LibreTranslate ](https://github.com/LibreTranslate/LibreTranslate) to the supported vendors? It would be nice to translate locally without sharing data with corporations.

Good idea! Need to investigate more. How big is this offline bundle with translations? 
Or it works just like normal vendor via some rest web apis?

**Comment by scavru** [comment]
I think offline is not needed, there are different distributions, for CPU and GPU. different languages. Just need api support, the server can be deployed anywhere, I put myself https://registry.hub.docker.com/r/libretranslate/libretranslate
project https://github.com/LibreTranslate/LibreTranslate
API docs https://libretranslate.com/docs/
