### ISSUE TITLE
XTranslate addon banned in Opera

### ISSUE THREAD

**Issue by stayathome** [ixrock/XTranslate#7]
https://addons.opera.com/ru/extensions/details/xtranslate/
![xtranslate - opera](https://cloud.githubusercontent.com/assets/10940040/21712326/d4bf3f3c-d3fc-11e6-8b38-c261f97efe16.png)

**Comment by stayathome** [comment]
![xtranslate - opera](https://cloud.githubusercontent.com/assets/10940040/21712317/c4972e9e-d3fc-11e6-93a7-43f358cf6dee.png)

**Comment by ixrock** [comment]
http://www.techsupportalert.com/content/how-install-chrome-extensions-opera.htm
