### ISSUE TITLE
Google translate stop working today!

### ISSUE THREAD

**Issue by led9** [ixrock/XTranslate#7]
Оther translaters work, google ballon message does not appear.
fix please.
And thank you for your wonderful extension! :)

**Comment by ixrock** [comment]
Thanks for report! I'm on vacation right now, will try to fix soon.

**Comment by denysdovhan** [comment]
the same problem. With Yandex works fine, but with google nothing appeares.

**Comment by ixrock** [comment]
fixed!

**Comment by denysdovhan** [comment]
thnx you! :+1:
