### ISSUE TITLE
Add favorites icon

### ISSUE THREAD

**Issue by EHMilon** [ixrock/XTranslate#70]
This is a great extension i recently explore this. Before using this extension i used **Rememberry** Extension. But **xTranslator** is more powerful and customizable extension. I love it. But this extension has not any icon/option to save important words & phrases. 
Plz add a favorite icon ⭐ beside the PopUp display to save words. This will help to Revision important words and phrases. 
There is a option to save history but it is quit hard to find words. 
Plz be considered.

**Comment by ixrock** [comment]
implemented in `v5.0.0` _(available in chrome store already)_

**Comment by EHMilon** [comment]
> implemented in `v5.0.0` _(available in chrome store already)_

**Thank you**, for adding a favorite icon. 
One request more, 
If you add favorites menu beside **Sitting**, **Popup**, **Translator**, **History** then **Favorites** on title bar. Then it will make easier to navigation.
Again, thank you. 
@ixrock
