### ISSUE TITLE
Pop-up requires manual activation on Firefox for some websites

### ISSUE THREAD

**Issue by steve-perkins** [ixrock/XTranslate#71]
I recently switched from (Chrome-based) Brave to Firefox.  For the most part, I have found XTranslate to work equally as well on both browsers.

However, occasionally I'll find a website where the pop-up behavior is partially broken.  In the Chrome version, highlighting some text brings up the "X" logo, which I can then click on to activate the translation pop-up.  However, on Firefox, highlighting the text does not bring up the "X" logo.

I CAN still activate the translation pop-up on these websites with Firefox.  But I have to right-click on the highlighted text, and select `Translate "..." with Google` from the XTranslate context menu.

For an example website to reproduce the issue, you can visit CNN en Español (https://cnnespanol.cnn.com/).  I am not sure what sites could be doing to make the pop-up behave differently (perhaps differences in Javascript engine?).  But this only happens on certain websites.  On the majority of websites, XTranslate works with Firefox just as it does with Chrome.

**Comment by ixrock** [comment]
Firefox not yet officially supported. 
See also: https://github.com/ixrock/XTranslate/issues/1
