### ISSUE TITLE
Text selection issues on touch screen devices

### ISSUE THREAD

**Issue by EHMilon** [ixrock/XTranslate#73]
I am using xtranslate on my Android device. But there are some bugs to select multiple sentence. If I disable **Display after right selection,** then xtranslate icon is too small. I cannot reach to touch this icon. 
![Screenshot_20231024-231223~2](https://github.com/ixrock/XTranslate/assets/107425940/c39d7f29-7b93-48a5-aaaf-3b055dc48b96)
But if I enable this option, I can not select multiple lines. If I try to do, then it will select hole website.

https://github.com/ixrock/XTranslate/assets/107425940/d1725c79-457d-421d-992a-45dc93593964

**Comment by ixrock** [comment]
Never tested the extension actually on android/touch devices.. 😬
If I would be able to reproduce the bug with chrome devtools / device simulation, then I'll fix it..

**Comment by EHMilon** [comment]
@ixrock 
Sorry to disturb you. I edited my issue. I add an image and a short video. For your clear understanding. I use Kiwi browser on my mobile device. Please check it out and fix the issue.

**Comment by ixrock** [comment]
@EHMilon thanks, but this is not top priority issue. Will be fixed at _some point_.

**Comment by EHMilon** [comment]
@ixrock Will you create an option in settings to enable and disable xtranslate icon. I found another way to translate. If I click on selected text or word it translate. So I don't need the icon. It will make the interface clear. This is an optional feature.

**Comment by ixrock** [comment]
@EHMilon This option is already exists:

<img width="607" alt="Screenshot 2023-10-25 at 19 17 47" src="https://github.com/ixrock/XTranslate/assets/6377066/e3f7d96a-1987-4244-acdd-8eb62116bcd4">

**Comment by EHMilon** [comment]
> This option is already exists:

@ixrock 
Sorry I just missed it. Thank you. 
You don't know how much helpful this extension to me. Thank you for creating this wonderful extension.
