### ISSUE TITLE
Add separate favorite menu bar

### ISSUE THREAD

**Issue by EHMilon** [ixrock/XTranslate#77]
In xtranslate extension homepage, there are 4 menus in titlebar. Settings, Pop Up, Translate and History. There are no separate menu bar for favorite section. If we need to open favorite section, we need to go History menu and click on the small star ⭐ icon. Please add separate menu bar. It will help us easy to access.
![Screenshot_20231024-234121~2](https://github.com/ixrock/XTranslate/assets/107425940/f6284b52-ae36-4fc4-8049-b975e9989d9e)

**Comment by ixrock** [comment]
Sorry, but no.. Favourites is a part of history and will be available only inside there. 
Also the extension's window width is very tight (about 600px max) and I don't wan't to have a horizontal scrollbar in tabs.
