### ISSUE TITLE
configurable position of the round button with x in it

### ISSUE THREAD

**Issue by guai** [ixrock/XTranslate#79]
Hi
On a touchscreen device when "Show translate-icon near selected text" option is checked and I select a word by long-tapping on it I got browser's default popup menu on top of the round x button covering it almost completely.
It would be better to make its position configurable.
<img width="403" alt="image" src="https://github.com/ixrock/XTranslate/assets/220780/b7bdf959-1619-4063-a61c-2ddfadbf8e64">

**Comment by ixrock** [comment]
You can select texts from right-to-left direction to get the icon on the left-top, that way you should have the icon visible, see:

https://github.com/ixrock/XTranslate/assets/6377066/8f86d158-2ec4-47d8-b75d-aec500b4d53e

**Comment by guai** [comment]
on touchscreen you can't do that. or at least can't do it easily enough.
you hold your finger on a word until it is selected.

**Comment by ixrock** [comment]
Feature is done, please wait update from chrome store in `>= v3.3.0`
