### ISSUE TITLE
can not find xtranslate on chrome web store

### ISSUE THREAD

**Issue by coder-free** [ixrock/XTranslate#81]
chrome version is  120.0.6099.216

**Comment by mehdihalla** [comment]
yes i too when open link from google search,  I receive 404 error cod .when i downloaded crx file from github and installed manually this extension, chrome disabled it.

**Comment by oleksii-boi** [comment]
That's what my Chrome told me 
<img width="474" alt="image" src="https://github.com/ixrock/XTranslate/assets/25286628/39d722e5-7ee0-43dd-a299-c2064f812628">

**Comment by alexweb** [comment]
Why it was flagged as unsafe?

**Comment by ixrock** [comment]
Yes, it is indeed the extension is marked as violating google chrome extensions store policies.

<img width="846" alt="image" src="https://github.com/ixrock/XTranslate/assets/6377066/fdbd2f77-ffb6-4104-9a11-9b3ba25d93ca">


When every user install the app you see this screen where you have 2 options: accept terms of usage of extension or delete app. Same version of the app is not violated in [Edge store](https://microsoftedge.microsoft.com/addons/detail/cinfaflgbaachkaamaeglolofeahelkd) for example.

<img width="762" alt="Screenshot 2024-01-16 at 14 46 19" src="https://github.com/ixrock/XTranslate/assets/6377066/8a36c004-a898-43fe-9f01-56ec7fe1ed24">

**Please read terms of usage carefully or simply uninstall the app.**



> Privacy Policy has been updated
> By using Chrome or Edge browser extension "XTranslate" you consent to this privacy policy and terms of use.
> 
> Privacy Policy Last updated: August 18, 2023
> 
> We are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy outlines how we collect, use, and safeguard the data you provide while using our Chrome extension.
> 
> Information We Collect: We do not collect any personally identifiable information (PII) when you use the "XTranslate". We do not request or store your name, email address, or any other personal details.
> Usage Data: To improve our services and enhance your gaming experience, we may collect non-personal, anonymous usage data. This may include information such as the number of games played and game duration. This data helps us analyze trends, understand user preferences, and make necessary improvements to the extension.
> Cookies: "XTranslate" does not use cookies or any tracking technologies to gather information about your browsing activities.
**> Affiliate Links "XTranslate" replaces URLs in the search result page with affiliate links. This means that when a user clicks on a search result and makes a purchase through the affiliate link, we (the developers of the Chrome Extension) receive a small commission from the retailer or service provider. This commission helps support the development, maintenance, and operation of the Service without any extra cost to users. It is 9 important to note that the use of affiliate links does not affect the quality or relevance of search results. The affiliate links are seamlessly integrated into the search results, ensuring a smooth browsing experience for users.**
> Third-Party Services: "XTranslate" does not integrate with or share data with any third-party services, websites, or applications.
> Changes to the Privacy Policy: We reserve the right to modify or update this Privacy Policy at any time. Any changes will be reflected on this page with the updated effective date. We encourage you to review this policy periodically to stay informed about how we protect your privacy. By using the "XTranslate", you agree to the terms and conditions outlined in this Privacy Policy.
> Some of generated user data, like history of translations might be stored via chrome.storage APIs (see more: https://developer.chrome.com/extensions/storage)
> This extension might use cookies & HTML 5 local storage in order to make the extension's work properly and provide consistent user experience
> As part of the functionality, the extension may send words you select to third-party translation services.
> Simply uninstall extension normally and all local user data will be erased, if you are not agreed with current terms & conditions.
> 

P.S. maybe in nearest future we will remove this for chrome and update chrome storage. Thanks for undestanding.

**Comment by a0s** [comment]
>Affiliate Links "XTranslate" replaces URLs in the search result page with affiliate links. 

Is it part of the sources at https://github.com/ixrock/XTranslate ?
I tried to find this in code with no success

**Comment by AGordey** [comment]
XTranslate started to work after some steps. chrome version is 120.0.6099.225
1) Open Extension->Manage Extension 
2) Open setting (screeshot) -> choose "leave this extension"
![image](https://github.com/ixrock/XTranslate/assets/91781472/ea183c4d-8850-4351-a74c-fc7f6de3efc7)
3) Switch on extension 
![image](https://github.com/ixrock/XTranslate/assets/91781472/09458f3c-5e6e-47fd-b939-18f037d9a559)

I hope developer fix problem with the Chrome Web Store policy.

**Comment by ixrock** [comment]
> > Affiliate Links "XTranslate" replaces URLs in the search result page with affiliate links.
> 
> Is it part of the sources at https://github.com/ixrock/XTranslate ? I tried to find this in code with no success

yes, it is, different branch (not main/master)
