### ISSUE TITLE
Extension has been removed from Google Store

### ISSUE THREAD

**Issue by i2van** [ixrock/XTranslate#85]
Extension has been removed from Google Store.

**Comment by ixrock** [comment]
Duplication, read: https://github.com/ixrock/XTranslate/issues/81#issuecomment-1893682725

**Comment by i2van** [comment]
The issue here that I can not install it for a new Chrome anymore since it is no longer available. Can you release binaries please?

**Comment by ixrock** [comment]
Ca you try to install it from [Edge store](https://microsoftedge.microsoft.com/addons/detail/cinfaflgbaachkaamaeglolofeahelkd)?

**Comment by i2van** [comment]
![image](https://github.com/ixrock/XTranslate/assets/5464660/f7d5e6be-da04-49f3-8426-0c649c7cc4ba)

**Comment by ixrock** [comment]
@i2van bad luck! Then I could recommend to use dev version of the app.
Enable development mode at `chrome://extensions/`, build extension and load `/dist` folder as said in [README](https://github.com/ixrock/XTranslate/blob/master/README.md#for-developers-and-contributors)
