### ISSUE TITLE
Extension deleted from chrome webstore?

### ISSUE THREAD

**Issue by esyede** [ixrock/XTranslate#86]
![image](https://github.com/ixrock/XTranslate/assets/10582583/ae8b51e7-9a6e-4e0b-bf9b-4b69c12c3366)
https://chrome.google.com/webstore/detail/xtranslate/gfgpkepllngchpmcippidfhmbhlljhoo

**Comment by AGordey** [comment]
https://github.com/ixrock/XTranslate/issues/81#issuecomment-1899145955

**Comment by esyede** [comment]
Leaving it open for now since no installable binaries found for new chrome installation

**Comment by elcarim** [comment]
Google Chrome deleted a package for me. Could someone share it so that I can install it and continue working as before?

**Comment by parsadoc** [comment]
Chrome deleted the package for me too!
this was a handy tool for me, So I had to run it locally from the source build!

**Comment by elcarim** [comment]
> Chrome deleted the package for me too! this was a handy tool for me, So I had to run it locally from the source build!

how to do it?

**Comment by parsadoc** [comment]
> > Chrome deleted the package for me too! this was a handy tool for me, So I had to run it locally from the source build!
> 
> how to do it?

1) download the source code
2) At the root of the project run the `yarn` command, to download dependencies.
3) then run the` yarn build` command to build the project.
3) open the Chrome extensions page and enable developer mode by checking the developer mode.
4) tap on the `Load unpacked` button in the top left and set the path to your dist (it paced in the root of the project) folder. 

I hope this extension back to the chrome market again.

**Comment by ixrock** [comment]
Update is sent to chrome web store for review.. Waiting..

**Comment by ixrock** [comment]
Restored.
