### ISSUE TITLE
Text-to-speech: silence

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ixrock/XTranslate#87]
Nothing happens when I click Play icon.

**Comment by ixrock** [comment]
what the translation service you use? page address? browser? app version? etc. otherwise text translations works fine?

**Comment by vitaly-zdanevich** [comment]
> what the translation service you use? 

Yandex

> page address?

For example this one.

> browser? app version?

Firefox 121.

**Comment by ixrock** [comment]
Firefox is not officially supported yet.
