### ISSUE TITLE
Permission: reduce to the current page only

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ixrock/XTranslate#89]
![image](https://github.com/ixrock/XTranslate/assets/3514015/ec9c8ace-e26c-4d89-926d-b5972a9270bb)

**Comment by ixrock** [comment]
this is required for loading data from external translation services (eg. goggle translate and some other services decides by developer)

**Comment by vitaly-zdanevich** [comment]
Hm, I remember that when I built this extension https://addons.mozilla.org/en-US/firefox/addon/intelligent-speaker-tts it also produce network calls, but with much less permission.
