### ISSUE TITLE
Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by RomeroMsk** [ixrock/XTranslate#9]
![screenshot_83](https://cloud.githubusercontent.com/assets/4639951/20051295/e1330058-a500-11e6-91d0-886727573bba.png)

Perhaps, it was started to rise after update to 1.200.

**Comment by ixrock** [comment]
Please provide url of page where it happens (or it's everywhere?)
And list of your installed extensions in chrome. Probably there are some conflicts..

**Comment by RomeroMsk** [comment]
It is private page, can't provide it.
Extension is still working as popup on extensions tollbar, and I don't use it for text selections.

The problem is in this part of code:
```
var b = document.getElementsByTagName("script")[0];
b.parentNode.insertBefore(a, b)
```
You are trying to get a `parentNode` with no check of element existence.

**Comment by ixrock** [comment]
Ok, I'll check! Thanks.

**Comment by RomeroMsk** [comment]
BTW, why do you change the content of each opened tab if text selection translate functional is turned off?
I want to use your extension just as standalone popup in my Chrome toolbar, and don't want to see unneeded `<app>` inside `<html>` or `<script>` inside `<body>` of each page I open.

**Comment by ixrock** [comment]
How did you turning it off?
Yeah, probably it a good idea to avoid appending app-tag to every page. Anyway I'm working on big update for the extension and it should fix all problems and add some more functionality. Hope to have enough time to release it around new year.

**Comment by ixrock** [comment]
The topic problem will be fixed in next update (already sent to chrome store).

**Comment by RomeroMsk** [comment]
> How did you turning it off?

I meant not turning on options in second section of display parameters.

> The topic problem will be fixed in next update (already sent to chrome store).

Cool, tnx.

**Comment by RomeroMsk** [comment]
> The topic problem will be fixed in next update (already sent to chrome store).

Checked, fixed. Thanks a lot!
