### ISSUE TITLE
[bug] it brokes page layout: adds footer

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ixrock/XTranslate#90]
In many pages, for example try here scroll to the bottom https://www.ethswarm.org/jobs/browser-extension-developer
![image](https://github.com/ixrock/XTranslate/assets/3514015/df4f8084-d576-486f-9392-3b6a6b546abf)

**Comment by ixrock** [comment]
Works for me, browser: **latest chrome**

**Comment by vitaly-zdanevich** [comment]
Try in Firefox.

**Comment by ixrock** [comment]
> Try in Firefox.

we don't support firefox officially..

**Comment by vitaly-zdanevich** [comment]
But you published in Mozilla store?

This issue will be solved if you add `display: none` when invisible, please.

**Comment by ixrock** [comment]
Yes, this is old version for manifest v2. Now it's totally outdated, but afaik mozilla don't support V3 fully. 
See also https://github.com/ixrock/XTranslate/issues/1

**Comment by vitaly-zdanevich** [comment]
Can I contribute a fix to the version that is currently published to Mozilla store?

**Comment by ixrock** [comment]
You can try. Make a PR to `firefox` branch and I'll re-upload it to mozilla store at some point.
