### ISSUE TITLE
Turn off mellowtel to use my bandwidth

### ISSUE THREAD

**Issue by EHMilon** [ixrock/XTranslate#98]
Please make it optional to share our network bandwidth with others.

**Comment by vitaly-zdanevich** [comment]
Wow, at minimum it MUST have the option to disable it.

Related link: https://github.com/mellowtel-inc/mellowtel-js

**Comment by ixrock** [comment]
It was always possible to disable it, just choose **Decline optional use** button at step 2:
_(every 2 weeks or maybe less often in future releases)_

**Step 1:**
<img width="609" alt="Screenshot 2024-09-22 at 16 57 27" src="https://github.com/user-attachments/assets/86680c61-c545-48ef-98d7-6b50a853e490">


**Step 2:**
<img width="612" alt="Screenshot 2024-09-22 at 16 57 33" src="https://github.com/user-attachments/assets/162ce18e-4bf3-462d-8e16-58e4ed7eb394">

**Step 3:**
Probably you also need to reload tabs or browser to take it in effect.

**Comment by EHMilon** [comment]
> It was always possible to disable it, just choose **Decline optional use**

**Decline Optional Use** mean _mellowtel_ will still use network bandwidth, but it will not share my data to their trusted partners. Am I wrong ???
If I am not wrong, then there should have an option that users can completely disable it, if they have concerned about their privacy and security.

You should find some sponsorship.
@ixrock

**Comment by ixrock** [comment]
@EHMilon `Decline Optional Use` button completely disable using MellowtelJS.

**UPD:** this button will call this function https://github.com/ixrock/XTranslate/blob/f72f5ac9cd0aecbadcfea17b0504d2805311afc8/mellowtel/mellowtel-lib.ts#L66

_By default, when you install extension, MellowtelJS always disabled!_
