### ISSUE TITLE
Migrate app build from webpack to esbuild

### ISSUE THREAD

**Issue by ixrock** [ixrock/XTranslate#99]
Since declared compilation speed is **10-100x faster** then `webpack`

More info: https://esbuild.github.io/

**Comment by vitaly-zdanevich** [comment]
Wow, guys, I believe that for such simple browser extension you do not need to use any frameworks and compilers at all...

**Comment by ixrock** [comment]
@vitaly-zdanevich This concept might be scaled, doesn't matter how simple currently it is.

**P.S.** though `webpack` does good enough for now. These are bundlers, not compilers :D

You can use ofc even plain vanilla JS on your choice :) But.. For long-term and big projects _(roughly >=50  code files on project)_ Typescript _is must_ have, I think..
